platform :ios, '7.0' 

#link_with [:SINotworking, :SINotworkingTests]
pod 'BETURLSession',    :git => 'https://github.com/screeninteraction/BETURLSession'
#pod 'BETURLSession', :path => '../../BETURLSession'

pod 'BETOAuth2Client', :path => '../'
