platform :ios, '7.0' 

#link_with [:SINotworking, :SINotworkingTests]
pod 'BETURLSession',    :git => 'https://github.com/screeninteraction/BETURLSession'  :tag =>'1.2'
#pod 'BETURLSession', :path => '../../BETURLSession'

pod 'BETOAuth2Client', :path => '../'
