platform :ios, '7.0' 

#link_with [:SINotworking, :SINotworkingTests]
pod 'BETURLSession', :git => 'https://github.com/screeninteraction/BETURLSession.git', :branch => :master
pod 'BETOAAuth2Client', :path => '../'
